# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots

# NB: don't set `language: haskell` here

sudo: false
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.local/

matrix:
  include:
    - env: STACKVER=1.7.1 STACK_RESOLVER=lts-12.4
    - env: STACKVER=1.7.1 STACK_RESOLVER=lts-11.17

# This is stack-specific.  Oh well.
before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - export STACK_YAML=stack-${STACK_RESOLVER}.yaml
 - export STACK_URL=https://github.com/commercialhaskell/stack/releases/download/v${STACKVER}/stack-${STACKVER}-linux-x86_64.tar.gz

install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:~/.local/bin:$PATH
 - ./.travis_install.sh
 - curl -sSL ${STACK_URL} | tar zxf - --strip-components=1 -C ~/.local/bin stack-${STACKVER}-linux-x86_64/stack
 - chmod a+x ~/.local/bin/stack
 - stack setup
 - stack build

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - stack test
